### ISSUE TITLE
Create data model for File Repository

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#37]
### Story
As an implementer, I want to understand where to capture Signal's file repository capabilities with FHIR resource types so I can store and retrieve a variety of files that are not related to the Patient care flow.

- UI screen still in development, but will include some of the following components:
   - Title
   - Filename 
   -  Classification file type (see image below)
   - Creator 
   - Start Period
- Will likely use the [DocumentReference](http://hl7.org/fhir/documentreference.html) resource type, see #38 
- Classification file type should be mapped to [LOINC](https://loinc.org/) codes, where possible
   - to be done by CLIENT
   - May also require custom code system for those that will not map
   - See `DocumentReference.type` binding in [US Core DocumentReference](https://hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference.html)

### Tasks:
- [x]  Create draft for Encounter relationships with FHIR resource types
- [x] Determine if we use [FHIR Core R4 DocumentReference](http://hl7.org/fhir/R4/documentreference.html) or [US Core DocumentReference](https://hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference.html)
- [x]  Create example workflow
- [x]  Document in the IG

![Current interface](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/28b4b179-113e-4a96-908c-555a8999f96d)
![Classification type](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/09f2abf9-6a5a-4a85-a7bb-544e29b6a170)
