### ISSUE TITLE
Create custom value set and code system for Organization

### ISSUE THREAD

**Issue by arunsundar-m** [enjoysparkling/signal-mso-fhir-profiles#60]
**Tasks**:

- [x] Identify elements needing customization
- [x] Collect codes, displays, and definitions for each element
- [x] Create custom CodeSystem(s)
- [x] Create custom ValueSet(s)
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation
   - [ ] Update terminology table
   - [ ] Update Organization Services Module to describe use of the custom code system

**Elements that need custom ValueSet (VS) and Code System (CS)**:
- Organization.type (VS)
   - [x] NPI Taxonomy (VS) - @enjoysparkling to provide table
   - [x] Signal organization hierarchy - service org, agency, provider (CS)
- Organization.qualification (VS, CS)
   - [x] Signal custom; e.g. ASAM, etc. @enjoysparkling to provide table

**Comment by enjoysparkling** [comment]
For NPI Taxonomy, use this ValueSet:  [Valueset-provider-taxonomy - FHIR v5.0.0 (hl7.org)](https://www.hl7.org/fhir/valueset-provider-taxonomy.html).  More information at https://www.cms.gov/medicare/provider-enrollment-and-certification/find-your-taxonomy-code

**Comment by enjoysparkling** [comment]
Signal qualifications... See note on Teams channel.  It might not be ASAM level, but through [Colorado LADDERS](https://[socgov06.my.salesforce-sites.com/LADDERS](https://socgov06.my.salesforce-sites.com/LADDERS))

**Comment by Gokulsignal** [comment]
Created the Code system and value set for the License Type - organization.qualification

**Comment by enjoysparkling** [comment]
> For NPI Taxonomy, use this ValueSet: [Valueset-provider-taxonomy - FHIR v5.0.0 (hl7.org)](https://www.hl7.org/fhir/valueset-provider-taxonomy.html). More information:

This ValueSet has nearly 900 values.  Presently the UI is a drop-down.  I would suggest it should be a TEXT field for the code only.  Then we don't need to expand it.

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/90017d1c-112d-4d67-b0b1-b4b7063d7d8b)

![image](https://github.com/enjoysparkling/signal-mso-fhir-profiles/assets/118555736/79da7867-c5f0-42e8-9cff-46c175778494)

**Comment by Gokulsignal** [comment]
Created the Value set (which includes 'Service Type' and 'License Type') for the organization.qualification .

**Comment by enjoysparkling** [comment]
Since we are overloading the `Organization.type` element, I recommend we create slices for each of the valuesets:
- NPI taxonomy
- Signal Org type hierarchy

**Comment by Gokulsignal** [comment]
@enjoysparkling Matt, Value set is created for the NPI taxonomy.
