### ISSUE TITLE
Create custom value set and code system for HealthcareService

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#61]
**Tasks**
- [x] Identify elements needing customization
- [x] Collect codes, displays, and definitions for each element
- [x] Create custom CodeSystem(s)
- [x] Create custom ValueSet(s)
- [x] @enjoysparkling to bring HealthcareService profile into Simplifier
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [x] HealthcareService.program (VS, CS) - @enjoysparkling to provide table
- [ ] HealthcareService.type 
   - [x]    - Service Types (VS, CS) - @enjoysparkling to provide table
   - [x]    - Procedure codes (CPT) (VS) - create a ValueSet with compose/expansion based on the USCSM
   - [ ]    - Modifier codes (CPT modifiers), TBD (VS) - create a ValueSet with compose/expansion based on the USCSM - @enjoysparkling to provide the table
- [x] HealthcareService.category (VS, CS)
   - [x] Service category (VS, CS) - @enjoysparkling to provide table

**Comment by enjoysparkling** [comment]
Recommended Program code system:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Signal name | Code | Display | Definition
-- | -- | -- | --
SUD | sud | Substance Use Disorder (SUD) | The substance use disorder   treatment license identifies the level of intensity of the services provided,   including residential, outpatient or withdrawal management (detox), and any   specialized populations an agency serves. Specialized populations include   individuals referred for treatment following a Driving Under the Influence   (DUI) conviction, individuals required through their involvement in the   criminal justice system to complete treatment as a part of a court sentence,   or mothers receiving treatment tailored to meet their needs. Intensity of   service ranges from once per week outpatient treatment all the way to   residential services.
Crisis | crisis | Colorado Crisis Services (CCS) | Colorado Crisis Services is the statewide behavioral   health crisis response system offering residents mental health, substance use   or emotional crisis help, information and referrals.
CYMHTA | cymhta | Children and Youth Mental Health Treatment Act   (CYMHTA) | The Children and Youth Mental   Health Treatment Act (CYMHTA) (C.R.S. 27-67-101, et. seq.), also called House   Bill 18-1094, allows for families to access mental health treatment services   for their child or youth. CYMHTA is an alternative to child welfare   involvement when a dependency and neglect action isn't warranted. CYMHTA   funding can be available when there is no other appropriate funding source   for treatment, such as private insurance.
Assessment | assessment | Assessment |  
Recovery | recovery | Recovery | Recovery Support Services.   According to the Substance Abuse and Mental Health   Services Administration (SAMHSA), recovery is a process of change through   which individuals with mental and/or substance use disorders improve their   health and wellness, live self-directed lives, and strive to reach their full   potential.




</body>

</html>

**Comment by enjoysparkling** [comment]
`HealthService.category`
Each CPT code falls into one of ten primary categories of service, or “Service categories”

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Code | Display | Definition
-- | -- | --
prevention-early-intervention | Prevention/Early   Intervention Services | Prevention   and Early Intervention Services include screening and outreach to identify   at-risk populations, proactive efforts to educate and empower Members to   choose and maintain healthy life behaviors and lifestyles that promote   behavioral health. Services can be population-based, including peer, and   group interventions, and are not restricted to face-to-face interventions.
crisis | Crisis   Services | Crisis/Emergency   Services are provided during a MH emergency, which can involve unscheduled, immediate,   or special interventions in response to a crisis with a member, including   associated laboratory services, as indicated.
screening | Screening   Services | Screening is   provided to address the needs of those seeking BH treatment services in a   timely manner. This brief assessment involves an initial appraisal of an   individual’s need for services.
assessment | Assessment   Services | Assessment   Services are the process, both initial and ongoing, of collecting and   evaluating information about a member for developing a profile on which to   base treatment/service planning and referral (2 CCR 502-1, 190.1).
treatment | Treatment   Services | Treatment   services utilize a variety of methods to treat mental, behavioral, and   substance use disorders. The goal is to alleviate emotional disturbances and   reverse or change maladaptive patterns of behavior in order to encourage a   member’s personal growth and development.
evaluation-management | Evaluation   and Management (E/M) Services | E/M codes   cover a broad range of services for members in both inpatient and outpatient   settings. They are generic in the sense that they are intended to be used by   all physicians, nurse[1]practitioners,   and physician assistants and to be used in primary and specialty care alike.
residential | Residential   Services | Residential   Services are any type of 24-hour care, excluding room and board, provided in   a non-hospital, non-nursing home (NH) setting, where the contractor provides   supervision in a therapeutic environment. Residential Services are   appropriate for children, youth, adults and older adults whose MH issues and   symptoms are severe enough to require a 24-hour structured program, but do not   require hospitalization.
respite | Respite Care   Services | Respite Care   Services are Temporary or short-term care of a child, adolescent or adult   provided by adults other than the birth parents, foster parents, adoptive   parents, family members or caregivers with whom the Member normally resides,   designed to give the usual caregivers some time away from the Member to allow   them to emotionally recharge and become better prepared to handle the normal   day-to-day challenges.
recovery | Peer   Support/Recovery Services | Peer   Support/Recovery Services are designed to provide choices and opportunities   for adults with SMIs, youth with SEDs, or individuals with SUDs.   Recovery-oriented services promote self-management of psychiatric symptoms,   relapse prevention, treatment choices, mutual support,    enrichment,   and rights protection. Peer Support/Recovery Services also provide social   supports and a lifeline for individuals who have difficulties developing and   maintaining relationships. These services can be provided at schools,   churches or other community locations.
support | Support   Services | Support   Services are not clinical but help facilitate a psychotherapy encounter and   include such supports as childcare for a member receiving clinical care,   Non-Emergent Medical Transportation (NEMT), and sign language services.




</body>

</html>

**Comment by enjoysparkling** [comment]
`healthService.type` for Service type (services):

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MATTZA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Level | Code | Display Value | Definition (Description)
-- | -- | -- | --
1 | sud | Substance Use Disorder (SUD) |  
2 | asam-0.5 | ASAM Level 0.5 - Early Intervention | Screening,   Brief Intervention and Referral for Treatment (SBIRT)
2 | asam-1 | ASAM Level 1.0   - Outpatient Services | Less than 9   hours of services /week (adults); less than 6 hours /week (adolescents) for   recovery or motivational enhancement therapies/strategies
2 | asam-2.1 | ASAM Level 2.1   - Intensive Outpatient Services (IOP) | 9 or more   hours of service /week (adults); 6 or more hours /week (adolescents) to treat   multi-dimensional instability
2 | asam-2.5 | ASAM Level 2.5   - Partial Hospitalization Services for adolescents and adults | 20 or more   hours of service /week (adults); 6 or more hours /week (adolescents) to treat   multi-dimensional instability
2 | asam-3.1 | ASAM Level 3.1   - Clinically Managed Low-Intensity Residential Services | 24 hour   structure with trained personnel; at least 5 hours of clinical service /week   and prepare for outpatient treatment
2 | asam-3.3 | ASAM Level 3.3   - Clinically Managed Population-Specific High-Intensity Residential Services | 24 hour   structure with trained counselors to stabilize multi-dimensional imminent   danger; Less intense milieu; and group treatment for those with cognitive or   other impairments unable to fill active milieu or therapeutic community and   prepare for outpatient treatment
2 | asam-3.5 | ASAM Level 3.5   - Clinically Managed High-Intensity Residential Services for adults | 24 hour care   with trained counselors to stabilize multi-dimensional imminent danger and   prepare for outpatient treatment
2 | asam-3.7 | ASAM Level 3.7   - Medically Monitored High-Intensity Inpatient Services for adolescents | 24 hour   nursing care with physician availability for significant problems in   Dimensions 1, 2 or 3. 16 hour/day counselor availability
2 | asam-4 | ASAM Level 4 -   Medically Managed Intensive Inpatient | 24 hour   nursing care and daily physician care for severe unstable problems in   Dimensions 1, 2 or 3. Counseling available to engage patient in treatment
2 | asam-1-wm | ASAM Level 1-WM   - Ambulatory Withdrawal Management Without Extended On-Site Monitoring | Mild withdrawal   with daily or less than daily outpatient supervision
2 | asam-2-wm | ASAM Level 2-WM   - Ambulatory Withdrawal Management with Extended On-site Monitoring | Moderate   withdrawal management and support and supervision; at night has supportive   family or living situation
2 | asam-3.2-wm | ASAM Level 3.2-WM    - Clinically Managed Residential   Withdrawal Management | Moderate   withdrawal, but needs 24 hour support to complete withdrawal management and   increase likelihood of continuing treatment or recovery
2 | asam-3.7-wm | ASAM Level 3.7-WM    - Medically Monitored Intensive   Inpatient Services Withdrawal Management for adults | Severe   withdrawal, 24-hour nursing care and physician visits; unlikely to complete   withdrawal management without medical monitoring.
2 | asam-otp | ASAM - Opioid   Treatment Program (OTP) | Daily or   several times weekly opioid agonist medication and counseling to maintain   multidimensional stability for those with severe opioid use
2 | asam-obot | ASAM - Office-Based   Opioid Treatment (OBOT) | Daily or   several times weekly opioid agonist medication and counseling to maintain   multidimensional stability for those with severe opioid use
2 | da | Differential Assessment |  
2 | ips | Individual   Placement Services |  
2 | dui-1 | DUI Level I Education |  
2 | dui-2-e | DUI Level II Education-only |  
2 | dui-2-te | DUI Level II Therapy and Education |  
1 | crisis | Crisis | Colorado   Crisis Services (CCS)
2 | mobile | Mobile |  
2 | atu-csu | ATU/CSU |  
2 | youth-csu | Youth CSU |  
2 | walk-in | Walk-in |  
2 | respite | Respite |  
2 | transportation | Transportation |  
1 | cymhta | CYMHTA | Children   and Youth Mental Health Treatment Act (CYMHTA)
2 | treatment | Treatment |  
2 | youth-residential | Youth residential |  
1 | assessment | Assessment |  
2 | Medicaid | Medicaid |  
2 | ffpsa | FFPSA |  
2 | cymhta | CYMHTA |  
1 | recovery | Recovery |  
2 | rss | Recovery Support Services (RSS) |  
2 | rlc | Recovery Living Community (RLC) |  




</body>

</html>

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, I have added the code system and value sets related to Healthcare Service and made commits to the enhancement branch tagged. Kindly review.

**Comment by enjoysparkling** [comment]
For creating the ValueSet for CPT and CPT Modifier, we will need to use these JSON files:
- ValueSet-cpt-base.json
- ValueSet-cpt-all.json
- ValueSet-cpt-active.json
- ValueSet-cpt-modifiers.json

[ValueSet-cpt.zip](https://github.com/enjoysparkling/signal-mso-fhir-profiles/files/12371413/ValueSet-cpt.zip)

Let me research, I'll provide instructions.

**Comment by enjoysparkling** [comment]
Added HealthcareService from FHIR R4 core.

**Comment by enjoysparkling** [comment]
Pull the HCPCS modifiers from https://hcpf.colorado.gov/sites/hcpf/files/July%202023%20USCS%20Manual%20Draft%20-Final.pdf

Code system:  https://terminology.hl7.org/5.0.0/CodeSystem-hcpcs-Level-II.html
Value set:  https://terminology.hl7.org/5.0.0/ValueSet-v3-HealthCareCommonProcedureCodingSystem.html  (modify to fit USCS manual)

**Comment by enjoysparkling** [comment]
I am going to create slices on `HealthcareService.type` to represent the different containers and bind the different value sets.
- .type:procedure
- .type:serviceCategory
- .type:procedureModifier

**Comment by arunsundar-m** [comment]
@enjoysparkling Hi Matt, I have run the forge validation and fixed the below valuesets.

Kindly review #https://github.com/enjoysparkling/signal-mso-fhir-profiles/commit/7b36651e6d92756082179537b7015e97d218dc70

1. valueset-birthsex.json

Removed `text`, `version`, `contact`

2. valueset-contact-entity-type.json

Removed `text`, `meta`, `contact`, `version`.
Added system in `expansion.contains`

3. valueset-detailed-ethnicity.json

Removed `text`, `version`, `contact`

4. valueset-detailed-race-category.json

Removed `text`, `version`, `contact`

5. valueset-identifier-type.json

Removed `text`, `meta`, `contact`, `version`.
Added system in `expansion.contains`

6. valueset-omb-ethnicity-category.json

Removed `text`, `version`, `contact`

7. ValueSet-omb-race-category.json

Removed `text`, `version`, `contact`

8. valueset-service-provision-conditions.json

Removed `text`, `meta`, `contact`, `version`.
Added system in `expansion.contains`

9. valueset-service-referral-method.json

Removed `text`, `meta`, `contact`, `version`.
Added system in `expansion.contains`

10. valueset-us-core-usps-state.json

Removed `text`, `version`, `contact`

Excluded the valuesets program, service-category and service-type as we have developed signal specific custom valuesets. Can we get rid of these valuesets? We can do a merge with the main branch as these might reflect in other branches.
