### ISSUE TITLE
Create custom value sets and code systems for Encounter

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#70]
**Tasks**
- [x] Identify elements needing customization
- [ ] Collect codes, displays, and definitions for each element
- [ ] Create custom CodeSystem(s)
- [ ] Create custom ValueSet(s)
- [ ] Bring in Encounter profile
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] Encounter.serviceType - bind to [HealthcareService Service type](https://github.com/enjoysparkling/signal-mso-fhir-profiles/blob/main/input/vocabulary/valueset-healthcare-service-type.json)
   - Delete example HL7 service type value set
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/46 
- [ ] Encounter.type - Utilize the HealthcareService procedure list (do we also need modifiers here??)
   - Edit or delete valueset-us-core-encounter-type.json, see definition of [extensible](http://hl7.org/fhir/R4/terminologies.html#extensible)
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/46

**Comment by arunsundar-m** [comment]
@enjoysparkling Can you please add the profiles to Simplifier and we can add them to the branch and do the bindings? we need to do the same for EpisodeOfCare, Service Request, and Procedure where we are reusing service-category, service-type, and procedure code valuesets for binding.

@Gokulsignal

**Comment by enjoysparkling** [comment]
@arunsundar-m - Give it a shot.  Follow my naming conventions. I'll review it.  This shouldn't be a blocker.  https://docs.fire.ly/projects/Forge/features/CreateDerivedProfiles.html
