### ISSUE TITLE
Create custom value sets and code systems for EpisodeOfCare

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#71]
**Tasks**
- [x] Identify elements needing customization
- [x] Collect codes, displays, and definitions for each element
- [x] Create custom CodeSystem(s)
- [x] Create custom ValueSet(s)
- [x] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] EpisodeOfCare.type - should probably represent the Service Type from the HealthcareService resource.  Keep this and include that code system.  We may also want to include Program code system into this ValueSet...
