### ISSUE TITLE
Create custom value sets and code systems for ServiceRequest

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#72]
**Tasks**
- [x] Identify elements needing customization
- [x] Collect codes, displays, and definitions for each element
- [x] Create custom CodeSystem(s)
- [x] Create custom ValueSet(s)
- [x] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] ServiceRequest.category - We should include the Service Type from HealthcareService, include it in this value set.
