### ISSUE TITLE
Create custom value sets and code systems for Procedure

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#73]
**Tasks**
- [ ] Identify elements needing customization
- [ ] Collect codes, displays, and definitions for each element
- [ ] Create custom CodeSystem(s)
- [ ] Create custom ValueSet(s)
- [ ] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] Procedure.category - We should include the Service Type from HealthcareService, include it in this value set `signal-healthcare-service-category`
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/49
- [ ] Procedure.code - covered by the one created in HealthcareService:  `healthcare-service-procedure-code-cpt`. Might have to be a subset, see definition of [extensible](http://hl7.org/fhir/R4/terminologies.html#extensible)
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/49
- [ ] Procedure.performer.function - might need to change this
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/49
- [ ] Procedure.followUp - might need to change this
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/49

**Comment by enjoysparkling** [comment]
These are not anticipated to change on Procedure.  We'll leave these available as ALL procedures (defined by US Core).
