### ISSUE TITLE
Create custom value sets and code systems for Practitioner

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#74]
**Tasks**
- [ ] Identify elements needing customization
- [ ] Collect codes, displays, and definitions for each element
- [ ] Create custom CodeSystem(s)
- [ ] Create custom ValueSet(s)
- [ ] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] Practitioner.qualification.code - We might need to change this, but we presently don't have Practitioner in our model.
