### ISSUE TITLE
Create custom value sets and code systems for PractitionerRole

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#75]
**Tasks**
- [ ] Identify elements needing customization
- [ ] Collect codes, displays, and definitions for each element
- [ ] Create custom CodeSystem(s)
- [ ] Create custom ValueSet(s)
- [ ] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [x] PractitionerRole.specialty - use NPI taxonomy from Organization.identifier:NPI
