### ISSUE TITLE
Create custom value sets and code systems for Location

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#76]
**Tasks**
- [ ] Identify elements needing customization
- [ ] Collect codes, displays, and definitions for each element
- [ ] Create custom CodeSystem(s)
- [ ] Create custom ValueSet(s)
- [ ] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] Location.type - we might need to repurpose this for Place of Service (POS)
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/50, [input/vocabulary/valueset-service-delivery-location-role-type.json](https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/50/files/d7459314fedfdf6e4240791f0e866d275643268d#diff-cbee1cd4f5cc4d7c0d08f7674fadb56b24a456b58fe9e6bdd6c09426b76124b5)
- [ ] Location.hoursofOperation.daysOfWeek - link from PractitionerRole value set
   - Ref https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/50
