### ISSUE TITLE
Create custom value sets / code systems for DocumentReference

### ISSUE THREAD

**Issue by enjoysparkling** [enjoysparkling/signal-mso-fhir-profiles#89]
**Tasks**
- [x] Identify elements needing customization
- [x] Collect codes, displays, and definitions for each element
- [x] Create custom CodeSystem(s)
- [x] Create custom ValueSet(s)
- [x] Bring in derived resource profile 
- [ ] Bind ValueSet(s) to profile
- [ ] Update documentation

**Elements that need custom ValueSet (VS) and Code System (CS)**
- [ ] .category ~~.type~~ 
   - [ ] - MAP LOINC codes - will need to include ADDITIONAL ValueSet with the Signal "Classifications".  Ideally, these concepts should be mapped to LOINC codes
   - [x] - Create expanded ValueSet and bind it

**Comment by enjoysparkling** [comment]
Latest list for File Classification:
- referral 
- assessment request 
- treatment record          (would include treatment plan, progress notes, discharge plan, discharge summary, release of information, client monthly progress report) 
- service authorizations  
- quality monitoring     (would include critical incident, grievance, waitlist tracker, utilization review, training report, denial report) 
- data submission            (would include compliance reports for MSO, episodic data for CCS) 
- invoice 
- Audit Requested Records 
- Credential Requested Records 
- Service Organization Feedback

**Comment by Gokulsignal** [comment]
Value set and Code System is created for the "Signal File Repo Classification" under the Document Reference.

**Comment by arunsundar-m** [comment]
@enjoysparkling @Gokulsignal I have made the naming convention changes, fixed the forge issues for code system and valueset for file-repo-classification #https://github.com/enjoysparkling/signal-mso-fhir-profiles/pull/104/commits/65d1dd0f81282199f2d8d2e92ecb852ae92073c5
